### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by maxcodefaster** [Tinkoff/micro-sentry#30]
# 🐞 Bug report

### Description
Thank you for merging the removal of the Angular HTTPPlugin. Sadly with the new release I am getting now a factory error:

```ts
TypeError: Cannot read properties of undefined (reading 'dsn')
    at new MicroSentryClient (micro-sentry-core.mjs:107:21)
    at new BrowserMicroSentryClient (micro-sentry-browser.mjs:19:9)
    at new MicroSentryService (micro-sentry-angular.mjs:42:1)
    at core.mjs:3722:21
    at Object.MicroSentryService_Factory [as factory] (micro-sentry-angular.mjs:56:1)
    at R3Injector.hydrate (core.mjs:9353:35)
    at R3Injector.get (core.mjs:9247:33)
    at injectInjectorOnly (core.mjs:4870:33)
    at Module.ɵɵinject (core.mjs:4874:12)
    at Object.MicroSentryErrorHandler_Factory [as factory] (micro-sentry-angular.mjs:76:1)
```

Gping back from 6.1.2 to 6.1.1 fixes the issue.

**Comment by IKatsuba** [comment]
@maxcodefaster  I am sorry for that! Please, use the latest version of the library
